### ISSUE TITLE
Phase One

### ISSUE THREAD

**Issue by jschneiderm98** [jschneiderm98/venturus-trial#1]
# Phase One

## Critérios de Aceitação 

- [ ] Prototype in Figma
- [ ] Layout: Team crud page
- [ ] Layout: My teams creation page
- [ ] My teams implementation
- [ ] Team CRUD implementation 
- [ ] Most/least picked player
